version: "3.7"


services:
  wgtcrm-web:
    build: ./docker/nginx
    image: devmagellan/wgtcrm-web:latest
    container_name: wgtcrm-web
    ports:
      - "8080:80"
    restart: always
    volumes:
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
      #- "./docker/nginx:/etc/nginx/conf.d"
      - "./:/var/www/html"
      - ./docker/nginx/logs:/var/log/nginx
    working_dir: /var/www/html
    depends_on:
      - "wgtcrm-php"
    networks:
      - wgtcrm


  wgtcrm-php:
    build:
        context: ./
        dockerfile: ./docker/php/Dockerfile
    container_name: wgtcrm-php
    image: devmagellan/wgtcrm-php:latest
    #environment:
      #APP_ENV: local
    restart: always
    working_dir: /var/www/html
    volumes:
      - "./docker/php:/usr/local/etc/php/"
      - "./:/var/www/html"
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      #/usr/local/etc/php/php.ini - real place
    ports:
      - "9000:9000"
    networks:
      - wgtcrm
    depends_on:
      - "wgtcrm-mysql"
    links:
      - "wgtcrm-mysql"
    secrets:
      - source: ssh_key
        target: /home/docker/.ssh/id_rsa

  rabbitmq:
     build:
        context: ./
        dockerfile: ./docker/rabbit/Dockerfile
     image: devmagellan/rabbitmq:latest
     hostname: app-rabbitmq
     ports:
       - 5672:5672
       - 15673:15673
     volumes:
       - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
     environment:
        RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
        RABBITMQ_DEFAULT_USER: imediasun
        RABBITMQ_DEFAULT_PASS: sunimedia
        RABBITMQ_DEFAULT_VHOST: /
     networks:
       - wgtcrm
     depends_on:
       - "wgtcrm-php"

  wgtcrm-mysql:
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    image: devmagellan/mysql:latest
    container_name: wgtcrm-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'production'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'sunimedia'
      MYSQL_ROOT_PASSWORD: 'sunimedia'
    ports:
      - '13306:3306'
    expose:
      - '3306'
    volumes:
      - "./docker/tmp/mysql:/var/lib/mysql"

    networks:
      - wgtcrm
  phpmyadmin:
      build:
         context: ./
         dockerfile: ./docker/myadmin/Dockerfile
      image: devmagellan/phpmyadmin:latest
      container_name: 'sc-phpmyadmin'
      links:
        - wgtcrm-mysql
      environment:
        PMA_HOST: wgtcrm-mysql
        PMA_PORT: 3306
      ports:
        - '8081:80'
      volumes:
        - /sessions
      depends_on:
        - "wgtcrm-mysql"
        - "wgtcrm-php"
      networks:
        - wgtcrm
networks:
  wgtcrm:
    name: wgtcrm
    driver: bridge
secrets:
  ssh_key:
    file: ~/.ssh/id_rsa
